language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script:
  - set -o pipefail
  - "mvn clean install -P release | egrep -v 'Download(ing|ed): '"

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2

before_cache: rm -rf $HOME/.m2/repository/org/tinylog
