language: java
sudo: false
install: true

jdk:
  - oraclejdk9
  - openjdk9

script:
  - mvn dependency:go-offline -q
  - mvn clean install -P release

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2

before_cache: rm -rf $HOME/.m2/repository/org/tinylog
